### ISSUE TITLE
Updated my handle but cannot import

### ISSUE THREAD

**Issue by Brdrker** [Ioni14/fleet-manager-extension#3]
Changed my handle (Rev_Temerity -> Dires_Traits). Updated Fleetmanager. If I try to import the json, my Fleetmanager page says the JSON is invalid. If I try to export from RSI hanger, I get told to contact this page.

I'm not sure the two are related but that's the use case scenario

**Comment by Ioni14** [comment]
Hello, I see your handle is actually Dires_Traits, so the change is successful.
But did you retry the export and did it succeed?

**Comment by Brdrker** [comment]
Yes... I tried both ways to do it.

When I tried "export to fleetmanager" I got the error message telling me to contact you via Git (used the link). I also tried "Export JSON file" but when I pointed the website to the JSON file, it considered it to be of an incorrect format. I then took the exported JSON file and fed it to FleetView and Fleetview had no issue with it.

Note: just the other day I removed the tag I was originally asked to place into my profile. I looked to "regenerate" that but had no luck.

Thoughts?

**Comment by Brdrker** [comment]
![FleetMgrExport](https://user-images.githubusercontent.com/21250895/70945041-4d88a880-2022-11ea-9a42-2065de14b258.JPG)

Just tried it again just now (Export to Fleet Manager)

**Comment by Ioni14** [comment]
Okay, thanks for the explanation and the screenshot.
Can you open the devtools (F12) go to Console tab, retry the Export and screenshot the console please?

**Comment by Ioni14** [comment]
And can you give me your fleet file (.json) please? It will be easier to check.

**Comment by Brdrker** [comment]
While you were writing, I was exporting a JSON to import directly. Got this result:

![FleetMgrJSONImport](https://user-images.githubusercontent.com/21250895/70945279-d6074900-2022-11ea-9938-e482256d265d.JPG)

**Comment by Brdrker** [comment]
JSON file generated. Saved as Txt file (because it wouldn't let me drag and drop the JSON).

[starcitizen-fleet.txt](https://github.com/Ioni14/fleet-manager-extension/files/3970262/starcitizen-fleet.txt)

**Comment by Brdrker** [comment]
Here is the console output:

![FleetMgrConsoleExport](https://user-images.githubusercontent.com/21250895/70945510-5e85e980-2023-11ea-8c11-a6cebd53d9cf.JPG)

**Comment by Brdrker** [comment]
It appears to be the same issue. Something in the JSON is causing FleetMgr to puke on the delivery of the data.

**Comment by Brdrker** [comment]
Not sure if this is related or not... I had just applied an upgrade to my Freelancer to become a Freelancer MAX before doing the export.

**Comment by Ioni14** [comment]
Thanks, I have all the data to investigate. I think this is a bug. Thanks again for reporting. ;)
I'll go back to you when I found the issue.

**Comment by Brdrker** [comment]
Thanks for your support!

**Comment by Ioni14** [comment]
I found the problem, the file validation was too strict. I will enhance it. Thanks to you. :)
I'll deploy a fix in a moment.

**Comment by Ioni14** [comment]
I'm curious, your "Standalone Ship - Endeavor Master Set Anniversary 2018", is it a referral? (The bug came from this ship).

**Comment by Brdrker** [comment]
No. I bought it during the Anniversary Sale before last. It was there the last time I imported. You can see it here:

https://fleet-manager.space/citizen/Dires_Traits

I did a direct export from the hanger to your site (aka I did not import a JSON at the site). BTW, our org is so big (ultimately) that every thing we tried to manage our fleet died from the number of ships. This site is WAY better in all sorts of ways. Our "leader" saw it and immediately had us start switching :)

**Comment by Ioni14** [comment]
Okay, in fact, the bug is that the "cost" property in the file must not be "null". (I'll change that). So if you want to update now, change the "null" to "$0.00". Otherwise, you can wait the fix. :)

I'm very happy to see that our app is useful. ;)
We try to make it the most stable we can, so we like when some awesome users like you report issues. :) It's very hard to detect this kind of bugs without reports.

**Comment by Brdrker** [comment]
I use to work at a major internet presence company... QA NEVER caught nearly as much as the users did. Hopefully, my "bug report" was enough to get you into the hunt. I have no problem generating data you need. Wonder why it's $0.00? it cost one heck of a lot more than THAT :(

**Comment by Brdrker** [comment]
Technically, it should be $1000.00 just so you know. I changed the value to that and it imported just fine.

"cost": "$1000.00 USD",

**Comment by Ioni14** [comment]
Oh, $0.00 was an example, but the extension has detected null so two possibilities:
- Your Hangar does not indicate the cost of the pledge
- Your Hangar indicates a cost in virtual money (not $).

Unfortunately, the data we can get are limited. :( We are waiting an official API from CIG...

**Comment by Brdrker** [comment]
For your records:

![EndeavorCostInHanger](https://user-images.githubusercontent.com/21250895/70948987-baa03c00-202a-11ea-95fd-ddc9e683c08a.JPG)

**Comment by Ioni14** [comment]
![Capture d’écran_2019-12-16_23-40-15](https://user-images.githubusercontent.com/7766609/70949175-6febe780-205d-11ea-90a8-8fa5a960c955.png)
Do you see the field cost in the HTML? Can you do the same for your ship?

**Comment by Brdrker** [comment]
Not trying to be a PITA. Here's the snippet from XPLOR (FleetView):

{
    "manufacturer": "MISC",
    "name": "Endeavor",
    "lti": true,
    "warbond": false,
    "package_id": "16136280",
    "pledge": "Standalone Ship - Endeavor Master Set Anniversary 2018",
    "pledge_date": "November 29, 2018",
    "cost": "$1,000.00 USD"
  },

Not sure how they got the 1k but just letting you know, somehow, they inserted that value. Again. thanks for the great program and the support!!!!

**Comment by Ioni14** [comment]
The fix has been deployed. Does it work now? :)
I think I will recheck the XPLOR plugin code, there's maybe something that has changed.

**Comment by Brdrker** [comment]
Yes, just did a direct export to FleetMgr and it went swimmingly. I can't generate your side page (kinda impressed that you get what you did). I used the Console as before and grabbed some code (picture) from the Endeavor:

![EndeavorCost](https://user-images.githubusercontent.com/21250895/70949935-297e9480-202d-11ea-87b2-9f8be2e466e5.JPG)

**Comment by Brdrker** [comment]
Configuration value IS $0.00.

**Comment by Ioni14** [comment]
Okay! you have reported 2 bugs in one. :joy: 
I haven't handled the thousand separator! (the comma).
I'm very sorry for this bug. :cry: 
I'll fix the webextension asap.

**Comment by Brdrker** [comment]
I'll shut up now. This is rapidly becoming a "while you are in there" kinda thing. I HATED that when I did development, much less system configurations "on the fly." :)

P.S. The following is a joke... but it reminds me of working in Operations while at that company I mentioned and the developers would expect ME to debug their code... LOL

![DebugMyCode](https://user-images.githubusercontent.com/21250895/70950550-f210e780-202e-11ea-98f1-1fb89ac754e0.jpg)

**Comment by Ioni14** [comment]
lol, as I said this kind of bugs is hard to detect in dev phase. :D
Typically, I didn't know that RSI put a comma as a thousand separator. ^^
But if you see the `tests` directory, you'll see that we have a pretty good test coverage. :wink:

**Comment by Brdrker** [comment]
It's kind of a BS thing for them to do... because if someone generates a CSV (not a far stretch to do this), then the CSV will have a 1, then a comma, then 000. Comma should be inserted upon RENDERING, not generation. I had the same problem at my new job. They were embedding formatting in the data. Ugh, no, not good :)

**Comment by Ioni14** [comment]
Yes, they must enclose with doublequotes in CSV like `"foobar","1,000"`.

**Comment by Ioni14** [comment]
You can update your extension to 1.0.8 (chrome will be available in some hours...). And re-export your fleet, the ship should cost $1,000. ;)

**Comment by Brdrker** [comment]
Thanks!
